### ISSUE TITLE
[ERROR] 关于游戏服务器端的公共IP设置问题

### ISSUE THREAD

**Issue by 1xxxxx5504** [EggLinks/DanhengServer-Public#10]
Unhandled exception. System.Net.Sockets.SocketException (99): Cannot assign requested address at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress) at System.Net.Sockets.Socket.Bind(EndPoint localEP) at EggLink.DanhengServer.Kcp.DanhengListener.StartListener() at EggLink.DanhengServer.Program.Program.EntryPoint.Main(String[] args) in D:\a\DanhengServer-Public\DanhengServer-Public\Program\Program\EntryPoint.cs:line 210

config.json如下：
{
  "HttpServer": {
    "PublicAddress": "4x.x.x.80",
    "PublicPort": 443,
    "UseSSL": true
  },
  "KeyStore": {
    "KeyStorePath": "certificate.p12",
    "KeyStorePassword": "123456"
  },
  "GameServer": {
    "PublicAddress": "4x.x.x.80",
    "PublicPort": 23301,
    "GameServerId": "dan_heng",
    "GameServerName": "DanhengServer",
    "GameServerDescription": "A re-implementation of StarRail server",
    "KcpInterval": 40
  },
  "Path": {
    "ResourcePath": "Resources",
    "ConfigPath": "Config",
    "DatabasePath": "Config/Database",
    "LogPath": "Logs",
    "PluginPath": "Plugins"
  },
  "Database": {
    "DatabaseType": "sqlite",
    "DatabaseName": "danheng.db",
    "MySqlHost": "4x.x.x.80",
    "MySqlPort": 3306,
    "MySqlUser": "root",
    "MySqlPassword": "123456",
    "MySqlDatabase": "danheng"
  },
  "ServerOption": {
    "StartTrailblazerLevel": 1,
    "AutoUpgradeWorldLevel": true,
    "EnableMission": true,
    "AutoLightSection": true,
    "Language": "CHS",
    "DefaultPermissions": [
      "*"
    ],
    "ServerAnnounce": {
      "EnableAnnounce": false,
      "AnnounceContent": "Welcome to danhengserver!"
    },
    "ServerProfile": {
      "Name": "Server",
      "Uid": 80,
      "Signature": "输入/help学习指令",
      "Level": 1,
      "HeadIcon": 200105,
      "ChatBubbleId": 220001,
      "DisplayAvatarId": 1001,
      "DisplayAvatarLevel": 1
    },
    "AutoCreateUser": true,
    "SavePersonalDebugFile": false
  },
  "DownloadUrl": {
    "AssetBundleUrl": null,
    "ExResourceUrl": null,
    "LuaUrl": null,
    "IfixUrl": null
  },
  "MuipServer": {
    "AdminKey": "196ad8c8-8a10-415a-a60c-5ec74a254613"
  }
}

如果你把GameServer的公共IP设置为服务器的公网ip，他会报错（如上），设置成127.0.0.1的话会导致无法进入服务器

**Comment by StopWuyu** [comment]
请提供系统类型(Windows / Linux)
以及Windows: `ipconfig/all`(可以部分打码敏感信息)
Linux `ifconfig -a` (同上)

**Comment by 1xxxxx5504** [comment]
br-4b3343b12f35: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 172.18.255.255
        ether 02:42:90:bf:8a:b0  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:eff:fe19:b16d  prefixlen 64  scopeid 0x20<link>
        ether 02:42:0e:19:b1:6d  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 128  bytes 14056 (14.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.21.106.217  netmask 255.255.240.0  broadcast 172.21.111.255
        inet6 fe80::216:3eff:fe04:bf0  prefixlen 64  scopeid 0x20<link>
        ether 00:16:3e:04:0b:f0  txqueuelen 1000  (Ethernet)
        RX packets 4022757  bytes 3304495956 (3.3 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2146406  bytes 362833355 (362.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 276308  bytes 73788638 (73.7 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 276308  bytes 73788638 (73.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by 1xxxxx5504** [comment]
这个错误使我无法让朋友加入服务器

**Comment by EggLink** [comment]
你是否使用的是类似阿里云弹性网卡这种网络？（好像是这个名字），你的可用ip中没有要绑定的公网ip，建议必应搜索类似新增虚拟网卡之类可能可以解决你的问题，或者更换网络类型等等（前者可能不会解决问题）

**Comment by 1xxxxx5504** [comment]
何时解决？

**Comment by 1xxxxx5504** [comment]
@EggLink 对，就是阿里云的服务器

**Comment by EggLink** [comment]
> 何时解决？

不，这与服务端无关，请检查你的服务器配置，尝试将ip地址修改为eth0的inet地址，再尝试连接

**Comment by 1xxxxx5504** [comment]
@EggLink 阿里云那边说无法修改网络类型，解决办法只有改代码（雾

**Comment by 1xxxxx5504** [comment]
看来这个东西它不适合云服务器啊（悲

**Comment by 1xxxxx5504** [comment]
@EggLink 在吗

**Comment by EggLink** [comment]
绑定172那个可不可以

**Comment by EggLink** [comment]
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
inet 172.21.106.217 netmask 255.255.240.0 broadcast 172.21.111.255
前面那个

**Comment by 1xxxxx5504** [comment]
我预估你们私服是登陆成功后是把GameServer的链接发给客户端，然后客户端进行连接，172的那个是阿里云内网
@EggLink

**Comment by 1xxxxx5504** [comment]
正在 Ping 172.21.106.217 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

**Comment by 1xxxxx5504** [comment]
不信你ping一个

**Comment by EggLink** [comment]
不 我的意思是单纯填写内网地址尝试绑定，阿里云的IP应该有映射，试试将http的ip写为内网，gameserver写成外网？不行的话我再改改吧

**Comment by EggLink** [comment]
完成后测试，是在哪个部分出现报错，请具体描述

**Comment by 1xxxxx5504** [comment]
@EggLink 我就是把GameServer写成公网ip才报错的,http的没问题

**Comment by 1xxxxx5504** [comment]
可以正常登录，但进不去游戏中

**Comment by 1xxxxx5504** [comment]
所以就导致的可以登录但进不去的情况

**Comment by EggLink** [comment]
> 所以就导致的可以登录但进不去的情况

我明白了 是能正常登录，但是点进入后提示1001_1错误？

**Comment by 1xxxxx5504** [comment]
应该是

**Comment by EggLink** [comment]
我明白了，我会将bind address 与 public address分开

**Comment by 1xxxxx5504** [comment]
谢谢哈，开发者辛苦了

**Comment by 1xxxxx5504** [comment]
@EggLink 好了吗

**Comment by lsqmuyu** [comment]
> @EggLink 好了吗

请耐心等候

**Comment by Deuteriunt** [comment]
@lsqmuyu 好的

**Comment by Deuteriunt** [comment]
> > @EggLink 好了吗
> 
> 请耐心等候

好的

**Comment by EggLink** [comment]
Try again
将config文件中的publicAddress编辑为真实公网IP再尝试
