### ISSUE TITLE
[BUG] 在击败镇守宝箱怪物后宝箱依旧没有解锁

### ISSUE THREAD

**Issue by morikawa56** [EggLinks/DanhengServer-Public#12]
使用的是7c47dea版本，在大世界击败镇守宝箱的怪物后宝箱上的红锁还在，虽然上面有了打开宝箱的提示但依旧无法打开。
![Snipaste_2024-09-03_13-19-16](https://github.com/user-attachments/assets/b57b0fc7-7091-471c-90c0-24a62ffca410)
![Snipaste_2024-09-03_13-19-29](https://github.com/user-attachments/assets/0429a297-0170-40c0-9141-cb08be5c3d14)

**Comment by StopWuyu** [comment]
暂时不会修复
