### ISSUE TITLE
[BUG] 角色异常消失

### ISSUE THREAD

**Issue by yunochan** [EggLinks/DanhengServer-Public#15]
**游戏内角色异常消失**
游戏内角色异常消失，但是查询MySQL数据库发现角色数据都还在。如果阵容存在消失的角色，那么玩家将卡在虚空，此时点击任何按钮都将导致黑屏。

**重现步骤**
我不知道如何触发这个BUG，这好像是概率触发。似乎与任务过场角色相关，当涉及到阵容的变更。

**预期行为**
数据库中角色数量应与游戏内仓库角色同步.

**截屏**
游戏内仓库角色计数19
![screen](https://github.com/user-attachments/assets/639aec95-eee0-4aa4-8f16-6c24c5c4e365)

**MySQL查询到的数据**
数据库角色计数57
[Avatar.json](https://github.com/user-attachments/files/17218531/Avatar.json)

**Comment by StopWuyu** [comment]
## 问题出现
```  
  { 19
        "AvatarId": 6023,
        "Level": 80,
        "Promotion": 6,
        "Timestamp": 1727793089,
        "CurrentHp": 10000,
        "ExtraLineupHp": 10000,
        "SkillTree": {},
        "SkillTreeExtra": {},
        "PathInfoes": {
            "6023": {
                "Rank": 6,
                "Relic": {}
            }
        }
    },
 ```
## 问题论述
我不明白是从哪里来的6023角色id 但是我想是遗留性问题，因为这个id对应的是斯科特任务中试用机甲，所以我认为只有一种可能
- 在以前使用过`giveall avatar`和使用了我们仓库内res [dumper问题导致将所有角色信息（包括试用角色）写进了一个文件，`giveall avatar` 会导致试用角色也给予，后续已修复，但可能会继承以前出现的问题]

## 解决方案
手动删除数据库内所有非 **1开头和非8001** 的角色，即删除所有除了下列角色id以外的所有角色信息
<details>
<summary>点击查看具体角色</summary>
1001: 三月七<br/>
1002: 丹恒<br/>
1003: 姬子<br/>
1004: 瓦尔特<br/>
1005: 卡芙卡<br/>
1006: 银狼<br/>
1008: 阿兰<br/>
1009: 艾丝妲<br/>
1013: 黑塔<br/>
1101: 布洛妮娅<br/>
1102: 希儿<br/>
1103: 希露瓦<br/>
1104: 杰帕德<br/>
1105: 娜塔莎<br/>
1106: 佩拉<br/>
1107: 克拉拉<br/>
1108: 桑博<br/>
1109: 虎克<br/>
1110: 玲可<br/>
1111: 卢卡<br/>
1112: 托帕&账账<br/>  
1201: 青雀<br/>
1202: 停云<br/>
1203: 罗刹<br/>
1204: 景元<br/>
1205: 刃<br/>
1206: 素裳<br/>
1207: 驭空<br/>
1208: 符玄<br/>
1209: 彦卿<br/>
1210: 桂乃芬<br/>
1211: 白露<br/>
1212: 镜流<br/>
1213: 丹恒•饮月<br/>  
1214: 雪衣<br/>
1215: 寒鸦<br/>
1217: 藿藿<br/>
1218: 椒丘<br/>
1220: 飞霄<br/>
1221: 云璃<br/>
1222: 灵砂<br/>
1223: 貊泽<br/>
1224: 三月七<br/>
1301: 加拉赫<br/>
1302: 银枝<br/>
1303: 阮•梅<br/>
1304: 砂金<br/>
1305: 真理医生<br/>
1306: 花火<br/>
1307: 黑天鹅<br/>
1308: 黄泉<br/>
1309: 知更鸟<br/>
1310: 流萤<br/>
1312: 米沙<br/>
1314: 翡翠<br/>
1315: 波提欧<br/>
8001: {NICKNAME}<br/>
8002: {NICKNAME}<br/>
8003: {NICKNAME}<br/>
8004: {NICKNAME}<br/>
8005: {NICKNAME}<br/>
8006: {NICKNAME}
</details>

**Comment by yunochan** [comment]
感谢你的帮助，此问题已解决。
