### ISSUE TITLE
[BUG] 含有短信的任务无法完成

### ISSUE THREAD

**Issue by redleaf1221** [EggLinks/DanhengServer-Public#20]
**Describe the bug**
一些含有短信的任务无法完成, 如202010403, 202010412. 任务中的短信内容显示为空白,结束短信后任务没有完成.

**Expected behavior**
任务应当正常完成.

**Additional context**
使用的服务端是Game 2.6.0 Release - 1109, Resources是先解压Dimbreath/turnbasedgamedata,再用EggLinks/DanhengServer-Resources中的Config覆盖

**Comment by Firefly5201314** [comment]
短信内容显示为空正常还没修

**Comment by Firefly5201314** [comment]
用/mission pass跳过

**Comment by EggLink** [comment]
> 用/mission pass跳过

请不要使用 `/mission pass`  它会造成一定的错误，请使用 `/mission finish <id>` 来完成
我会尝试修复他

**Comment by redleaf1221** [comment]
另外,任务202030207的短信结束后游戏黑屏.

**Comment by Firefly5201314** [comment]
好的

**Comment by EggLink** [comment]
try to reaccept it and do it again if u want
