### ISSUE TITLE
[DMCA TACKDOWN!]仓库Dimbreath/StarRailData被DMCA下架，求补档!!!

### ISSUE THREAD

**Issue by 1xxxxx5504** [EggLinks/DanhengServer-Public#21]
Repository unavailable due to DMCA takedown.
This repository is currently disabled due to a DMCA takedown notice. We have disabled public access to the repository. The notice has been [publicly posted](https://github.com/github/dmca/blob/master/2024/10/2024-10-10-hoyoverse.md).

If you are the repository owner, and you believe that your repository was disabled as a result of mistake or misidentification, you have the right to file a counter notice and have the repository reinstated. Our help articles provide more details on our [DMCA takedown policy](https://docs.github.com/articles/dmca-takedown-policy) and [how to file a counter notice](https://docs.github.com/articles/guide-to-submitting-a-dmca-counter-notice). If you have any questions about the process or the risks in filing a counter notice, we suggest that you consult with a lawyer.

**Comment by 1xxxxx5504** [comment]
@EggLink @StopWuyu

**Comment by NecroticGlow** [comment]
https://gitlab.com/Dimbreath/turnbasedgamedata
