### ISSUE TITLE
[ERROR]iOS访问会获取全局分发错误

### ISSUE THREAD

**Issue by 1xxxxx5504** [EggLinks/DanhengServer-Public#22]
手机上:
Version:8177649_V2.6Live_CNPRODiOS2.6.0
StageCode:1
ErrorCode:0
终端输出无任何可疑问题
@StopWuyu @EggLink

**Comment by HanLuLL** [comment]
进门的时候服务端有client request么？亦或者说你是改了什么还是模块什么的，说清楚点啊

**Comment by 1xxxxx5504** [comment]
看了一下Fiddler，每次请求都是502

**Comment by 1xxxxx5504** [comment]
@HanLuLL

**Comment by EggLink** [comment]
请检查代理

**Comment by 1xxxxx5504** [comment]
import System;
import System.Windows.Forms;
import Fiddler;
import System.Text.RegularExpressions;

class Handlers
{
    static function OnBeforeRequest(oS: Session) {
        if (oS.host.EndsWith(".starrails.com") || oS.host.EndsWith(".hoyoverse.com") || oS.host.EndsWith(".mihoyo.com") || oS.host.EndsWith(".bhsr.com") || oS.host.EndsWith(".hksr.com")) {
            oS.oRequest.headers.UriScheme = "http";
            oS.host = "192.168.1.30"; // This can also be replaced with another IP address.
        }
    }
};
有问题吗？

**Comment by 1xxxxx5504** [comment]
{
  "HttpServer": {
    "BindAddress": "0.0.0.0",
    "PublicAddress": "127.0.0.1",
    "Port": 443,
    "UseSSL": false
  },
  "KeyStore": {
    "KeyStorePath": "certificate.p12",
    "KeyStorePassword": "123456"
  },
  "GameServer": {
    "BindAddress": "0.0.0.0",
    "PublicAddress": "127.0.0.1",
    "Port": 23301,
    "GameServerId": "dan_heng",
    "GameServerName": "DanhengServer",
    "GameServerDescription": "A re-implementation of StarRail server",
    "UsePacketEncryption": true
  },
  "Path": {
    "ResourcePath": "Resources",
    "ConfigPath": "Config",
    "DatabasePath": "Config/Database",
    "LogPath": "Logs",
    "PluginPath": "Plugins"
  },
  "Database": {
    "DatabaseType": "sqlite",
    "DatabaseName": "danheng.db",
    "MySqlHost": "127.0.0.1",
    "MySqlPort": 3306,
    "MySqlUser": "root",
    "MySqlPassword": "123456",
    "MySqlDatabase": "danheng"
  },
  "ServerOption": {
    "StartTrailblazerLevel": 1,
    "AutoUpgradeWorldLevel": true,
    "EnableMission": true,
    "AutoLightSection": true,
    "Language": "CHS",
    "FallbackLanguage": "EN",
    "DefaultPermissions": [
      "*"
    ],
    "ServerAnnounce": {
      "EnableAnnounce": true,
      "AnnounceContent": "Welcome to danhengserver!"
    },
    "ServerProfile": {
      "Name": "Server",
      "Uid": 80,
      "Signature": "Type /help for a list of commands",
      "Level": 1,
      "HeadIcon": 200105,
      "ChatBubbleId": 220001,
      "DisplayAvatarId": 1001,
      "DisplayAvatarLevel": 1
    },
    "AutoCreateUser": true,
    "SavePersonalDebugFile": false
  },
  "DownloadUrl": {
    "AssetBundleUrl": null,
    "ExResourceUrl": null,
    "LuaUrl": null,
    "IfixUrl": null
  },
  "MuipServer": {
    "AdminKey": "edcc949d-cc93-4133-b7ef-ea5dde2f61c7"
  }
}

**Comment by 1xxxxx5504** [comment]
用的iPhone手机连Fiddler来玩的

**Comment by 1xxxxx5504** [comment]
@EggLink

**Comment by 1xxxxx5504** [comment]
？

**Comment by EggLink** [comment]
设置public address至手机连接的内网IP
