### ISSUE TITLE
[BUG] Calyx Rewards don't scale with battle count

### ISSUE THREAD

**Issue by guimenezessouza** [EggLinks/DanhengServer-Public#5]
**Describe the bug**
A 6-attempt calyx run (60 tb power) only gives rewards as if I ran one attempt (10 tb power)

**To Reproduce**
1. Go to a Calyx
2. Change attempts to 6
3. Completing this run only gives rewards as if running one attempt

**Expected behavior**
Rewards should scale according to the number of attempts selected in each run, like it does on the regular game.

**Screenshots**
![image](https://github.com/EggLink/DanhengServer-Public/assets/69261617/87bdde4f-f9d1-4729-aae8-b4f10dfff3ea)

**Additional context**
I know giving myself items is possible, but since this PS already made an effort to enable missions I believe fixing this would help even more with making it feel like the actual game.

**Comment by StopWuyu** [comment]
This problem may not fix at soon
at least before the basic function implemented
